class asdg_slotInfo;
class asdg_frontSideRail: asdg_slotInfo {
    class compatibleItems {
        TIERONE_RAILS_NGAL(Tier1_NGAL_Side)
        TIERONE_RAILS_NGAL(Tier1_NGAL_Top)
        TIERONE_RAILS_NGAL(Tier1_M4BII_NGAL_Top)
        TIERONE_RAILS_NGAL(Tier1_M4BII_NGAL_Side)
        TIERONE_RAILS_NGAL_FL(Tier1_M4BII_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_M4BII_NGAL_M300C_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_M4BII_NGAL_M600V)
        TIERONE_RAILS_NGAL_FL(Tier1_M4BII_NGAL_M600V_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_M4BII_NGAL_M603V)
        TIERONE_RAILS_NGAL(Tier1_Mk18_NGAL_Top)
        TIERONE_RAILS_NGAL(Tier1_Mk18_NGAL_Side)
        TIERONE_RAILS_NGAL_FL(Tier1_Mk18_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_Mk18_NGAL_M300C_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_Mk18_NGAL_M600V)
        TIERONE_RAILS_NGAL_FL(Tier1_Mk18_NGAL_M600V_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_Mk18_NGAL_M603V)
        TIERONE_RAILS_NGAL(Tier1_MP7_NGAL_Side)
        TIERONE_RAILS_NGAL_FL(Tier1_MP7_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_MP7_NGAL_M300C_Black)
        TIERONE_RAILS_NGAL(Tier1_SCAR_NGAL_Side)
        TIERONE_RAILS_NGAL(Tier1_SCAR_NGAL_Top)
        TIERONE_RAILS_NGAL_FL(Tier1_SCAR_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_SCAR_NGAL_M300C_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_SCAR_NGAL_M600V)
        TIERONE_RAILS_NGAL_FL(Tier1_SCAR_NGAL_M600V_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_SCAR_NGAL_M603V)
        TIERONE_RAILS_LA5(Tier1_LA5_Side)
        TIERONE_RAILS_LA5(Tier1_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_SCAR_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_SCAR_LA5_Side)
        TIERONE_RAILS_LA5_FL(Tier1_SCAR_LA5_M300C)
        TIERONE_RAILS_LA5_FL(Tier1_SCAR_LA5_M300C_Black)
        TIERONE_RAILS_LA5_FL(Tier1_SCAR_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_SCAR_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_SCAR_LA5_M603V)
        TIERONE_RAILS_LA5(Tier1_M4BII_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_M4BII_LA5_Side)
        TIERONE_RAILS_LA5_FL(Tier1_M4BII_LA5_M300C)
        TIERONE_RAILS_LA5_FL(Tier1_M4BII_LA5_M300C_Black)
        TIERONE_RAILS_LA5_FL(Tier1_M4BII_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_M4BII_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_M4BII_LA5_M603V)
        TIERONE_RAILS_LA5(Tier1_Mk18_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_Mk18_LA5_Side)
        TIERONE_RAILS_LA5_FL(Tier1_Mk18_LA5_M300C)
        TIERONE_RAILS_LA5_FL(Tier1_Mk18_LA5_M300C_Black)
        TIERONE_RAILS_LA5_FL(Tier1_Mk18_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_Mk18_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_Mk18_LA5_M603V)
        TIERONE_RAILS_LA5(Tier1_MP7_LA5_Side)
        TIERONE_RAILS_LA5_FL(Tier1_MP7_LA5_M300C)
        TIERONE_RAILS_LA5_FL(Tier1_MP7_LA5_M300C_Black)
        TIERONE_RAILS_LA5(Tier1_M249_LA5_Side)
        TIERONE_RAILS_LA5_FL(Tier1_M249_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_M249_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_M249_LA5_M603V)
    };
};

class tier1_SMR145_Slot: asdg_frontSideRail {
    class compatibleItems {
        TIERONE_RAILS_NGAL(Tier1_145_NGAL_Side)
        TIERONE_RAILS_NGAL(Tier1_145_NGAL_Top)
        TIERONE_RAILS_NGAL_FL(Tier1_145_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_145_NGAL_M600V)
        TIERONE_RAILS_NGAL_FL(Tier1_145_NGAL_M600V_alt)
        TIERONE_RAILS_NGAL_FL(Tier1_145_NGAL_M603V)
    };
};

class tier1_SMR10_Slot: asdg_frontSideRail {
    class compatibleItems {
        TIERONE_RAILS_NGAL(Tier1_10_NGAL_Side)
        TIERONE_RAILS_NGAL(Tier1_10_NGAL_Top)
        TIERONE_RAILS_NGAL_FL(Tier1_10_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_10_NGAL_M600V)
        TIERONE_RAILS_NGAL_FL(Tier1_10_NGAL_M600V_alt)
        TIERONE_RAILS_NGAL_FL(Tier1_10_NGAL_M603V)
        TIERONE_RAILS_LA5(Tier1_10_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_10_LA5_Side)
        TIERONE_RAILS_LA5_FL(Tier1_10_LA5_M300C)
        TIERONE_RAILS_LA5_FL(Tier1_10_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_10_LA5_M600V_alt)
        TIERONE_RAILS_LA5_FL(Tier1_10_LA5_M603V)
    };
};

class tier1_RAHG_Slot: asdg_frontSideRail {
    class compatibleItems {
        TIERONE_RAILS_NGAL(Tier1_RAHG_NGAL_Side)
        TIERONE_RAILS_NGAL(Tier1_RAHG_NGAL_Top)
        TIERONE_RAILS_NGAL_FL(Tier1_RAHG_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_RAHG_NGAL_M600V)
        TIERONE_RAILS_NGAL_FL(Tier1_RAHG_NGAL_M600V_alt)
        TIERONE_RAILS_NGAL_FL(Tier1_RAHG_NGAL_M603V)
        TIERONE_RAILS_LA5_FL(Tier1_RAHG_LA5_M300C)
        TIERONE_RAILS_LA5_FL(Tier1_RAHG_LA5_M300C_Black)
        TIERONE_RAILS_LA5_FL(Tier1_RAHG_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_RAHG_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_RAHG_LA5_M600V_alt)
        TIERONE_RAILS_LA5_FL(Tier1_RAHG_LA5_M600V_alt_Black)
        TIERONE_RAILS_LA5_FL(Tier1_RAHG_LA5_M603V)
        TIERONE_RAILS_LA5(Tier1_RAHG_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_RAHG_LA5_Side)
    };
};

class tier1_Midwest_Slot: asdg_frontSideRail {
    class compatibleItems {
        TIERONE_RAILS_NGAL(Tier1_MW_NGAL_Side)
        TIERONE_RAILS_NGAL(Tier1_MW_NGAL_Top)
        TIERONE_RAILS_NGAL_FL(Tier1_MW_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_MW_NGAL_M300C_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_MW_NGAL_M600V)
        TIERONE_RAILS_NGAL_FL(Tier1_MW_NGAL_M600V_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_MW_NGAL_M600V_alt)
        TIERONE_RAILS_NGAL_FL(Tier1_MW_NGAL_M600V_alt_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_MW_NGAL_M603V)
        TIERONE_RAILS_LA5_FL(Tier1_MW_LA5_M300C)
        TIERONE_RAILS_LA5_FL(Tier1_MW_LA5_M300C_Black)
        TIERONE_RAILS_LA5_FL(Tier1_MW_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_MW_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_MW_LA5_M600V_alt)
        TIERONE_RAILS_LA5_FL(Tier1_MW_LA5_M600V_alt_Black)
        TIERONE_RAILS_LA5_FL(Tier1_MW_LA5_M603V)
        TIERONE_RAILS_LA5(Tier1_MW_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_MW_LA5_Side)
    };
};

class tier1_URX4_Slot: asdg_frontSideRail {
    class compatibleItems {
        TIERONE_RAILS_NGAL(Tier1_URX4_NGAL_Side)
        TIERONE_RAILS_NGAL(Tier1_URX4_NGAL_Top)
        TIERONE_RAILS_NGAL_FL(Tier1_URX4_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_URX4_NGAL_M300C_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_URX4_NGAL_M600V)
        TIERONE_RAILS_NGAL_FL(Tier1_URX4_NGAL_M600V_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_URX4_NGAL_M600V_alt)
        TIERONE_RAILS_NGAL_FL(Tier1_URX4_NGAL_M600V_alt_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_URX4_NGAL_M603V)
        TIERONE_RAILS_LA5(Tier1_URX4_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_URX4_LA5_Side)
        TIERONE_RAILS_LA5_FL(Tier1_URX4_LA5_M300C)
        TIERONE_RAILS_LA5_FL(Tier1_URX4_LA5_M300C_Black)
        TIERONE_RAILS_LA5_FL(Tier1_URX4_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_URX4_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_URX4_LA5_M600V_alt)
        TIERONE_RAILS_LA5_FL(Tier1_URX4_LA5_M600V_alt_Black)
        TIERONE_RAILS_LA5_FL(Tier1_URX4_LA5_M603V)
     };
};

class tier1_MCX_Slot: asdg_frontSideRail {
    class compatibleItems {
        TIERONE_RAILS_NGAL(Tier1_MCX_NGAL_Side)
        TIERONE_RAILS_NGAL(Tier1_MCX_NGAL_Top)
        TIERONE_RAILS_NGAL_FL(Tier1_MCX_NGAL_M300C)
        TIERONE_RAILS_NGAL_FL(Tier1_MCX_NGAL_M300C_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_MCX_NGAL_M600V)
        TIERONE_RAILS_NGAL_FL(Tier1_MCX_NGAL_M600V_Black)
        TIERONE_RAILS_NGAL_FL(Tier1_MCX_NGAL_M603V)
        TIERONE_RAILS_LA5_FL(Tier1_MCX_LA5_M300C)
        TIERONE_RAILS_LA5_FL(Tier1_MCX_LA5_M300C_Black)
        TIERONE_RAILS_LA5_FL(Tier1_MCX_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_MCX_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_MCX_LA5_M603V)
        TIERONE_RAILS_LA5(Tier1_MCX_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_MCX_LA5_Side)
     };
};

class Tier1_SR25_Slot: asdg_frontSideRail
{
	class compatibleItems {
        TIERONE_RAILS_LA5(Tier1_SR25_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_SR25_LA5_Side)
	};
};
class Tier1_M110_Slot: asdg_frontSideRail
{
	class compatibleItems {
        TIERONE_RAILS_LA5(Tier1_M110_LA5_Top)
        TIERONE_RAILS_LA5(Tier1_M110_LA5_Side)
	};
};
class Tier1_Mk46Mod0_Slot: asdg_frontSideRail
{
	class compatibleItems {
        TIERONE_RAILS_LA5(Tier1_Mk46Mod0_LA5)
        TIERONE_RAILS_LA5_FL(Tier1_Mk46Mod0_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_Mk46Mod0_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_Mk46Mod0_LA5_M603V)
    };
};
class Tier1_Mk46Mod1_Slot: asdg_frontSideRail
{
	class compatibleItems {
        TIERONE_RAILS_LA5(Tier1_Mk46Mod1_LA5)
        TIERONE_RAILS_LA5_FL(Tier1_Mk46Mod1_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_Mk46Mod1_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_Mk46Mod1_LA5_M603V)
	};
};
class Tier1_Mk48Mod0_Slot: asdg_frontSideRail
{
	class compatibleItems {
        TIERONE_RAILS_LA5_FL(Tier1_Mk48Mod0_LA5)
        TIERONE_RAILS_LA5_FL(Tier1_Mk48Mod0_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_Mk48Mod0_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_Mk48Mod0_LA5_M603V)
    };
};
class Tier1_Mk48Mod1_Slot: asdg_frontSideRail
{
	class compatibleItems {
        TIERONE_RAILS_LA5_FL(Tier1_Mk48Mod1_LA5)
        TIERONE_RAILS_LA5_FL(Tier1_Mk48Mod1_LA5_M600V)
        TIERONE_RAILS_LA5_FL(Tier1_Mk48Mod1_LA5_M600V_Black)
        TIERONE_RAILS_LA5_FL(Tier1_Mk48Mod1_LA5_M603V)
    };
};






